// Maps a browser KeyboardEvent.code (physical, layout-independent) to the
// matching Windows virtual-key code, for use with user32.SendInput directly
// (see injectorWin32.ts). Mirrors keyMap.ts's CODE_TO_KEY one-for-one --
// same set of codes, same Cmd->Ctrl rationale for MetaLeft/MetaRight -- just
// targeting raw VK constants instead of nut.js's Key enum. Modifier,
// navigation, and function keys are layout-invariant in Windows, so this
// table is safe for real key-hold semantics (shortcuts, arrows, Ctrl/Alt/
// Shift combos); actual character typing goes through injectorWin32's
// separate KEYEVENTF_UNICODE path instead (see docs/native-input-plan.md),
// which is layout-independent by construction and doesn't use this table.
export interface VkEntry {
  vk: number
  // KEYEVENTF_EXTENDEDKEY is required for these keys to be recognized
  // correctly (arrows, Insert/Delete/Home/End/PgUp/PgDn, the right-hand
  // Ctrl/Alt, NumLock, Print Screen, and the numpad's Enter/Divide) --
  // without it Windows can misinterpret them as their numpad/left-hand
  // twins since the base VK code alone doesn't disambiguate.
  extended?: boolean
}

export const CODE_TO_VK: Partial<Record<string, VkEntry>> = {
  Escape: { vk: 0x1b },
  F1: { vk: 0x70 },
  F2: { vk: 0x71 },
  F3: { vk: 0x72 },
  F4: { vk: 0x73 },
  F5: { vk: 0x74 },
  F6: { vk: 0x75 },
  F7: { vk: 0x76 },
  F8: { vk: 0x77 },
  F9: { vk: 0x78 },
  F10: { vk: 0x79 },
  F11: { vk: 0x7a },
  F12: { vk: 0x7b },
  F13: { vk: 0x7c },
  F14: { vk: 0x7d },
  F15: { vk: 0x7e },
  F16: { vk: 0x7f },
  F17: { vk: 0x80 },
  F18: { vk: 0x81 },
  F19: { vk: 0x82 },
  F20: { vk: 0x83 },
  F21: { vk: 0x84 },
  F22: { vk: 0x85 },
  F23: { vk: 0x86 },
  F24: { vk: 0x87 },
  PrintScreen: { vk: 0x2c, extended: true },
  ScrollLock: { vk: 0x91 },
  Pause: { vk: 0x13 },
  Backquote: { vk: 0xc0 },
  Digit1: { vk: 0x31 },
  Digit2: { vk: 0x32 },
  Digit3: { vk: 0x33 },
  Digit4: { vk: 0x34 },
  Digit5: { vk: 0x35 },
  Digit6: { vk: 0x36 },
  Digit7: { vk: 0x37 },
  Digit8: { vk: 0x38 },
  Digit9: { vk: 0x39 },
  Digit0: { vk: 0x30 },
  Minus: { vk: 0xbd },
  Equal: { vk: 0xbb },
  Backspace: { vk: 0x08 },
  Insert: { vk: 0x2d, extended: true },
  Home: { vk: 0x24, extended: true },
  PageUp: { vk: 0x21, extended: true },
  NumLock: { vk: 0x90, extended: true },
  NumpadEqual: { vk: 0x92 },
  NumpadDivide: { vk: 0x6f, extended: true },
  NumpadMultiply: { vk: 0x6a },
  NumpadSubtract: { vk: 0x6d },
  NumpadAdd: { vk: 0x6b },
  NumpadEnter: { vk: 0x0d, extended: true },
  NumpadDecimal: { vk: 0x6e },
  Numpad0: { vk: 0x60 },
  Numpad1: { vk: 0x61 },
  Numpad2: { vk: 0x62 },
  Numpad3: { vk: 0x63 },
  Numpad4: { vk: 0x64 },
  Numpad5: { vk: 0x65 },
  Numpad6: { vk: 0x66 },
  Numpad7: { vk: 0x67 },
  Numpad8: { vk: 0x68 },
  Numpad9: { vk: 0x69 },
  Tab: { vk: 0x09 },
  KeyQ: { vk: 0x51 },
  KeyW: { vk: 0x57 },
  KeyE: { vk: 0x45 },
  KeyR: { vk: 0x52 },
  KeyT: { vk: 0x54 },
  KeyY: { vk: 0x59 },
  KeyU: { vk: 0x55 },
  KeyI: { vk: 0x49 },
  KeyO: { vk: 0x4f },
  KeyP: { vk: 0x50 },
  BracketLeft: { vk: 0xdb },
  BracketRight: { vk: 0xdd },
  Backslash: { vk: 0xdc },
  Delete: { vk: 0x2e, extended: true },
  End: { vk: 0x23, extended: true },
  PageDown: { vk: 0x22, extended: true },
  CapsLock: { vk: 0x14 },
  KeyA: { vk: 0x41 },
  KeyS: { vk: 0x53 },
  KeyD: { vk: 0x44 },
  KeyF: { vk: 0x46 },
  KeyG: { vk: 0x47 },
  KeyH: { vk: 0x48 },
  KeyJ: { vk: 0x4a },
  KeyK: { vk: 0x4b },
  KeyL: { vk: 0x4c },
  Semicolon: { vk: 0xba },
  Quote: { vk: 0xde },
  Enter: { vk: 0x0d },
  ShiftLeft: { vk: 0xa0 },
  KeyZ: { vk: 0x5a },
  KeyX: { vk: 0x58 },
  KeyC: { vk: 0x43 },
  KeyV: { vk: 0x56 },
  KeyB: { vk: 0x42 },
  KeyN: { vk: 0x4e },
  KeyM: { vk: 0x4d },
  Comma: { vk: 0xbc },
  Period: { vk: 0xbe },
  Slash: { vk: 0xbf },
  ShiftRight: { vk: 0xa1 },
  ArrowUp: { vk: 0x26, extended: true },
  ControlLeft: { vk: 0xa2 },
  // See keyMap.ts's CODE_TO_KEY for the Cmd->Ctrl rationale -- same trade-off
  // applies here since this table backs the same keydown/keyup path.
  MetaLeft: { vk: 0xa2 },
  AltLeft: { vk: 0xa4 },
  Space: { vk: 0x20 },
  AltRight: { vk: 0xa5, extended: true },
  MetaRight: { vk: 0xa3, extended: true },
  ContextMenu: { vk: 0x5d, extended: true },
  ControlRight: { vk: 0xa3, extended: true },
  ArrowLeft: { vk: 0x25, extended: true },
  ArrowDown: { vk: 0x28, extended: true },
  ArrowRight: { vk: 0x27, extended: true },
  AudioVolumeMute: { vk: 0xad, extended: true },
  AudioVolumeDown: { vk: 0xae, extended: true },
  AudioVolumeUp: { vk: 0xaf, extended: true },
  MediaPlayPause: { vk: 0xb3, extended: true },
  MediaStop: { vk: 0xb2, extended: true },
  MediaTrackNext: { vk: 0xb0, extended: true },
  MediaTrackPrevious: { vk: 0xb1, extended: true }
}
